"""Connector configuration management with Fernet-based secret encryption."""

import json
import logging
import os
import threading
from typing import Any, Dict, List, Optional

from cryptography.fernet import Fernet
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

logger = logging.getLogger("connector_config")


def _get_db_url() -> str:
    from PVE2Services.libs.db_adapter import resolve_db_url
    return resolve_db_url()


_STRICT_SECRETS = os.getenv("PVE2_STRICT_SECRETS", "false").lower() in ("1", "true", "yes")

# Config values that must never be stored in plaintext
SECRET_FIELDS = frozenset({
    "api_key",
    "proxmox_secret",
    "wiki_token",
    "pihole_token",
    "adguard_password",
    "ssh_key",
    "telegram_bot_token",
    "discord_webhook_url",
    "slack_webhook_url",
    "mattermost_webhook_url",
    # PVE2LLM (Winky) provider credentials
    "openai_api_key",
    "anthropic_api_key",
    "ollama_api_key",
})

_DEFAULT_KEY_FILE = os.getenv("PVE2_ENCRYPTION_KEY_FILE", ".pve2_encryption_key")


def _load_or_create_key() -> bytes:
    """Return the Fernet key, auto-generating and persisting one if needed.

    Precedence: PVE2_ENCRYPTION_KEY env > persisted key file > new key file.
    The key file is created with 0600 perms next to the app (like .pve2_secret);
    deleting it makes previously stored secrets undecryptable.
    """
    env_key = os.getenv("PVE2_ENCRYPTION_KEY")
    if env_key:
        return env_key.encode()
    if os.path.exists(_DEFAULT_KEY_FILE):
        with open(_DEFAULT_KEY_FILE, "r", encoding="utf-8") as f:
            return f.read().strip().encode()
    key = Fernet.generate_key()
    try:
        with open(_DEFAULT_KEY_FILE, "w", encoding="utf-8") as f:
            f.write(key.decode())
        os.chmod(_DEFAULT_KEY_FILE, 0o600)
    except OSError:
        logger.warning("Cannot persist encryption key to %s; secrets will not survive restart decryption", _DEFAULT_KEY_FILE)
    return key


def _get_fernet() -> Optional[Fernet]:
    if _STRICT_SECRETS:
        key = os.getenv("PVE2_ENCRYPTION_KEY")
        if not key:
            logger.error("PVE2_STRICT_SECRETS=true but PVE2_ENCRYPTION_KEY not set — refusing to store secrets")
            raise RuntimeError("PVE2_ENCRYPTION_KEY is required when PVE2_STRICT_SECRETS=true")
        return Fernet(key.encode())
    try:
        return Fernet(_load_or_create_key())
    except Exception:
        logger.exception("Failed to initialize secret encryption")
        return None


def encrypt_value(plaintext: str) -> str:
    f = _get_fernet()
    if f:
        return f.encrypt(plaintext.encode()).decode()
    logger.warning("Encryption unavailable; storing secret in plaintext")
    return plaintext


def decrypt_value(ciphertext: str) -> str:
    f = _get_fernet()
    if f:
        try:
            return f.decrypt(ciphertext.encode()).decode()
        except Exception:
            # Value was stored before encryption was enabled — return as-is
            return ciphertext
    return ciphertext


_config_lock = threading.Lock()
_config_instance: Optional["ConnectorConfig"] = None


def get_config_manager() -> "ConnectorConfig":
    """Return a thread-safe singleton ConnectorConfig instance."""
    global _config_instance
    if _config_instance is None:
        with _config_lock:
            if _config_instance is None:
                _config_instance = ConnectorConfig()
    return _config_instance


class ConnectorConfig:
    """Manages connector configurations and sync state with encrypted secrets."""

    def __init__(self):
        self.db_url = _get_db_url()
        self.engine: Engine = create_engine(self.db_url, future=True)
        self._ensure_schema()

    def _ensure_schema(self):
        # SQLite: INTEGER PRIMARY KEY auto-aliases the rowid; Postgres needs
        # an explicit identity so INSERT statements can omit `id`.
        if self.engine.dialect.name == "postgresql":
            pk_sql = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        else:
            pk_sql = "id INTEGER PRIMARY KEY"
        schema_sql = [
            f"""CREATE TABLE IF NOT EXISTS connector_config (
                {pk_sql},
                connector_id TEXT UNIQUE NOT NULL,
                enabled BOOLEAN DEFAULT FALSE,
                config TEXT NOT NULL DEFAULT '{{}}',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )""",
            f"""CREATE TABLE IF NOT EXISTS connector_sync_state (
                {pk_sql},
                connector_id TEXT UNIQUE NOT NULL,
                last_sync_at TIMESTAMP,
                last_sync_status TEXT DEFAULT 'pending',
                sync_count INTEGER DEFAULT 0,
                error_count INTEGER DEFAULT 0,
                last_error TEXT,
                items_synced INTEGER DEFAULT 0,
                FOREIGN KEY(connector_id) REFERENCES connector_config(connector_id)
            )"""
        ]
        try:
            with self.engine.begin() as conn:
                for sql in schema_sql:
                    conn.execute(text(sql))
        except Exception as e:
            logger.warning("Schema creation issue (may already exist): %s", e)

    def get_config(self, connector_id: str) -> Dict[str, Any]:
        try:
            with self.engine.connect() as conn:
                row = conn.execute(
                    text("SELECT config FROM connector_config WHERE connector_id = :id"),
                    {"id": connector_id}
                ).fetchone()
                if row:
                    raw = json.loads(row[0])
                    for k in SECRET_FIELDS & raw.keys():
                        if isinstance(raw[k], str) and raw[k]:
                            raw[k] = decrypt_value(raw[k])
                    return raw
            return {}
        except Exception as e:
            logger.error("Error getting config for %s: %s", connector_id, e)
            return {}

    def save_config(self, connector_id: str, config: Dict[str, Any], enabled: bool = False) -> bool:
        try:
            cfg = dict(config)
            for k in SECRET_FIELDS & cfg.keys():
                if isinstance(cfg[k], str) and cfg[k]:
                    cfg[k] = encrypt_value(cfg[k])
            config_json = json.dumps(cfg)
            with self.engine.begin() as conn:
                # Portable upsert (SQLite >=3.24 and Postgres): a second
                # save must not rely on a failed INSERT followed by an
                # UPDATE inside the same transaction — on Postgres the
                # failed INSERT aborts the transaction and the UPDATE
                # would be rejected (InFailedSqlTransaction).
                conn.execute(
                    text("""INSERT INTO connector_config (connector_id, config, enabled)
                            VALUES (:id, :config, :enabled)
                            ON CONFLICT (connector_id)
                            DO UPDATE SET
                                config = EXCLUDED.config,
                                enabled = EXCLUDED.enabled,
                                updated_at = CURRENT_TIMESTAMP"""),
                    {"id": connector_id, "config": config_json, "enabled": bool(enabled)}
                )
            logger.info("Connector %s config saved", connector_id)
            return True
        except Exception as e:
            logger.error("Error saving config for %s: %s", connector_id, e)
            return False

    def get_sync_state(self, connector_id: str) -> Dict[str, Any]:
        try:
            with self.engine.connect() as conn:
                row = conn.execute(
                    text("""SELECT last_sync_at, last_sync_status, sync_count, error_count,
                                   last_error, items_synced
                            FROM connector_sync_state WHERE connector_id = :id"""),
                    {"id": connector_id}
                ).fetchone()
                if row:
                    return {
                        "last_sync_at": row[0],
                        "last_sync_status": row[1],
                        "sync_count": row[2],
                        "error_count": row[3],
                        "last_error": row[4],
                        "items_synced": row[5],
                    }
            return {"last_sync_at": None, "last_sync_status": "pending", "sync_count": 0,
                    "error_count": 0, "last_error": None, "items_synced": 0}
        except Exception as e:
            logger.error("Error getting sync state for %s: %s", connector_id, e)
            return {"last_sync_at": None, "last_sync_status": "error", "sync_count": 0,
                    "error_count": 1, "last_error": str(e), "items_synced": 0}

    def update_sync_state(self, connector_id: str, status: str = "success",
                          error: Optional[str] = None, items_synced: int = 0) -> bool:
        try:
            with self.engine.begin() as conn:
                existing = conn.execute(
                    text("SELECT id FROM connector_sync_state WHERE connector_id = :id"),
                    {"id": connector_id}
                ).fetchone()
                if not existing:
                    conn.execute(
                        text("INSERT INTO connector_sync_state (connector_id) VALUES (:id)"),
                        {"id": connector_id}
                    )
                if status == "success":
                    conn.execute(
                        text("""UPDATE connector_sync_state
                                SET last_sync_at = CURRENT_TIMESTAMP,
                                    last_sync_status = :status,
                                    sync_count = sync_count + 1,
                                    items_synced = :items,
                                    last_error = NULL
                                WHERE connector_id = :id"""),
                        {"status": status, "items": items_synced, "id": connector_id}
                    )
                else:
                    conn.execute(
                        text("""UPDATE connector_sync_state
                                SET last_sync_at = CURRENT_TIMESTAMP,
                                    last_sync_status = :status,
                                    error_count = error_count + 1,
                                    last_error = :error
                                WHERE connector_id = :id"""),
                        {"status": status, "error": error, "id": connector_id}
                    )
            return True
        except Exception as e:
            logger.error("Error updating sync state for %s: %s", connector_id, e)
            return False

    def list_connectors(self) -> List[Dict[str, Any]]:
        """List all configured connectors with their enabled status."""
        try:
            with self.engine.connect() as conn:
                rows = conn.execute(
                    text("SELECT connector_id, enabled, updated_at FROM connector_config ORDER BY connector_id")
                ).fetchall()
                return [{"connector_id": r[0], "enabled": bool(r[1]), "updated_at": r[2]} for r in rows]
        except Exception as e:
            logger.error("Error listing connectors: %s", e)
            return []

    def delete_config(self, connector_id: str) -> bool:
        """Delete a connector's configuration."""
        try:
            with self.engine.begin() as conn:
                conn.execute(
                    text("DELETE FROM connector_config WHERE connector_id = :id"),
                    {"id": connector_id}
                )
                conn.execute(
                    text("DELETE FROM connector_sync_state WHERE connector_id = :id"),
                    {"id": connector_id}
                )
            return True
        except Exception as e:
            logger.error("Error deleting config for %s: %s", connector_id, e)
            return False
